### ISSUE TITLE
Using with MUI Typography dont work well because the balancer is not working when I increase width of screen.

### ISSUE THREAD

**Issue by gbrl-almeida** [shuding/react-wrap-balancer#29]
I believe some adjust may fix this. The balancer work when I decrease screen width. But, next, when increase back, its not working

**Comment by shuding** [comment]
Can you create a simple reproduction? Maybe using CodeSandbox?

**Comment by teobler** [comment]
https://codesandbox.io/s/material-demo-forked-fvf9b?file=/demo.js

didn't observe any bugs in my case, may need more detail about this @gbrl-almeida
