### ISSUE TITLE
Feature Request: Allow It to Size According to Parent's Height

### ISSUE THREAD

**Issue by dukesx** [shuding/react-wrap-balancer#37]
## Problem
When put in a constrained parent, it does not size well , it does wrapping very well but for responsive designs ? Doesn't look so good. Especially , if you are creating article cards that need responsive titles with constrained "line clamp" or height. 

### Use Cases
1. Responsive Designs
2. Constrained Parent
3. Carousel/Cards

**Comment by shuding** [comment]
Can you share a concrete example? Like a screenshot or something that explains what do you want and how it behaves.

> it does not size well , it does wrapping very well but for responsive designs ? Doesn't look so good
