### ISSUE TITLE
React 17 Support

### ISSUE THREAD

**Issue by AmirTugi** [shuding/react-wrap-balancer#38]
Hi!
React 17 is not supporting `React.useId()`

I'm getting an error for this.  

![image](https://user-images.githubusercontent.com/8065975/216363700-9c363a3e-2437-4096-b94b-91526ee482cb.png)

Can we add a support for an alternative if the react version is 17?

I read [here](https://github.com/reactwg/react-18/discussions/111#discussioncomment-1517837) about a possible alternative.

**Comment by shuding** [comment]
Using an alternative can potentially break if you have SSR... but I guess the case will be rare for React 17. So yeah we can consider accepting a PR for this.
