### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by DestroyerXyz** [shuding/react-wrap-balancer#46]
Next 13.2.1 with appdir
React 18.2.0

I have a React server component with only text wrapped in <Balancer> tags and it produces this error

**Comment by shuding** [comment]
I can't reproduce this problem, could you share a https://stackblitz.com link that reproduces it?

**Comment by shuding** [comment]
Closing as inactivity. Happy to reopen if there's anything we can do.
