### ISSUE TITLE
Add progressive enhancement for browser support of `text-wrap: balance`

### ISSUE THREAD

**Issue by mrchrishahn** [shuding/react-wrap-balancer#48]
It seems like there will soon be a first browser implementation for `text-wrap: balance` shipped in Chrome.
- https://groups.google.com/a/chromium.org/g/blink-dev/c/f5eLz6PIXaI/m/R__N3BdjAAAJ
- https://drafts.csswg.org/css-text-4/#text-wrap

It would be great to add a progressive enhancement that adds the `text-wrap: balance` style when supported by browsers, in turn deactivating the "manual" implementation of react-wrap-balancer. Would give people the peace of mind that in the future react-wrap-balancer would work more as a polyfill. 

Happy to create an implementation and PR if desired.

**Comment by shuding** [comment]
Happy to accept a PR for it, but here're my thoughts: although this lib is more like an implementation of the spec, it still provides extra features like the balance ratio value. And then, it might be tricky to smoothly switch between this lib and native CSS to do the balancing (as you can't detect where the client supports the native balancing or not, during SSR).

That said, I'm still very excited to see that if there's chance to find a viable path!
