### ISSUE TITLE
Safari Error: ReferenceError: Can't find variable: ResizeObserver — 

### ISSUE THREAD

**Issue by stephan227** [shuding/react-wrap-balancer#5]
Balancer will crash safari and display the error: ReferenceError: Can't find variable: ResizeObserver —

**Comment by shuding** [comment]
What's the Safari version? https://caniuse.com/resizeobserver

**Comment by stephan227** [comment]
> What's the Safari version? https://caniuse.com/resizeobserver

13.0

**Comment by so1ve** [comment]
> > What's the Safari version? [caniuse.com/resizeobserver](https://caniuse.com/resizeobserver)
> 
> 13.0

ResizeObserver isn't available in safari 13.0

**Comment by shuding** [comment]
We should add a Compatibility section in the readme. `ResizeObserver` is needed by this lib, you can consider add a polyfill for it.

**Comment by thebuilder** [comment]
Just a heads up, that #18 also means a polyfill needs to be be included before the first `<script>` block. 
I agree the client should ensure the ResizeObserver is provided, but might it be a good service in the initial `relayout` function to ensure the `ResizeObserver` exists, if it's not critical?

**Comment by shuding** [comment]
@thebuilder I think if `ResizeObserver` doesn't exist, we can silently ignore `ResizeObserver` for production builds (`process.env.NODE_ENV === 'production'`). For development we can output a console error.

I think it's OK to have potential layout shifts for browsers that don't support `ResizeObserver` (and not polyfilled), comparing to a error that breaks the website.

**Comment by mrgnou** [comment]
Anyway we could have [this](https://github.com/shuding/react-wrap-balancer/issues/5#issuecomment-1372800632) implemented? It would avoid the need of installing a polyfill for such a small amount of users.
