### ISSUE TITLE
Script injection conflicts with CSP rules

### ISSUE THREAD

**Issue by frec-kenneth** [shuding/react-wrap-balancer#51]
We serve our site with CSP rules preventing script injections. This component is throwing a visible next.js error in dev:
```
Unhandled Runtime Error
TypeError: self[u] is not a function

Call Stack
MutationObserver.n
node_modules/react-wrap-balancer/dist/index.mjs (2:1692)
```

This is only visible when the page renders a Balancer with SSR.

There are also CSP errors in the console.
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://*.googleapis.com https://*.googletagmanager.com 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...='), or a nonce ('nonce-...') is required to enable inline execution.
```

Suggestion: remove inline script injection, or at least allow a hash/nonce to be used.

**Comment by shuding** [comment]
Agreed to have a new `nonce` prop for both `Balancer` and `Provider` 👍
