### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by thomaswang** [shuding/react-wrap-balancer#52]
On Version 111.0.1 (64-bit)

![CleanShot 2023-03-31 at 19 31 35@2x](https://user-images.githubusercontent.com/41944255/229250187-0167c18d-a8fa-4863-8ac5-5bcb310a4933.png)
![CleanShot 2023-03-31 at 19 31 30@2x](https://user-images.githubusercontent.com/41944255/229250200-b2527ee6-5e3e-4b40-b734-85003a277865.png)

**Comment by shuding** [comment]
Is there any console log?

**Comment by thomaswang** [comment]
@shuding weird, can't reproduce it now, was on Starbucks WiFi earlier. Will re-open if I see it again!
