### ISSUE TITLE
Script gets into the website title tag

### ISSUE THREAD

**Issue by jahirfiquitiva** [shuding/react-wrap-balancer#53]
Hi, for some reason the script used for the balancer is getting into the website title meta tags

![Shot 2023-04-12 at 00 14 23@2x](https://user-images.githubusercontent.com/10360816/231357106-993065f3-152b-412c-9b81-6ec24297059b.png)

Is there a way to avoid this issue? otherwise, could you please look into it? thanks!

**Comment by jahirfiquitiva** [comment]
It looks like this only happens if the balancer is used with an `h1`

![Shot 2023-04-12 at 01 07 51@2x](https://user-images.githubusercontent.com/10360816/231367324-aafe5095-28c0-47b5-abb5-ed1f18a2cf5d.png)

![Shot 2023-04-12 at 01 12 03@2x](https://user-images.githubusercontent.com/10360816/231367299-edc8260c-d493-4501-a12d-4d1aff917b56.png)

**Comment by shuding** [comment]
The SEO tool you are using seems to be implemented incorrectly, it might be using something like `$('h1').innerText` and search engines shouldn't be affect.

**Comment by jahirfiquitiva** [comment]
@shuding do you have a suggestion on where to test the metatags? 🤔
