### ISSUE TITLE
Error while using it with Next.Js 13

### ISSUE THREAD

**Issue by anthonyhexium** [shuding/react-wrap-balancer#7]
Hi there,

Don't know if it's due to Next.Js or not.

But when impletementing the lib it actually works but I am getting an error in my console.

![CleanShot 2022-12-23 at 15 53 44](https://user-images.githubusercontent.com/62936624/209355552-0ef6b781-721a-490d-8762-0ca48157074a.png)

Any idea about it ? 

Thanks for helping.

**Comment by MananTank** [comment]
Me too!

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/22043396/209355830-85eba213-a13b-4649-b0d0-ca339dc40add.png">

**Comment by dextermb** [comment]
I've ran into this as well.

**Comment by anthonyhexium** [comment]
> I've ran into this as well.

Also with Next.js ? 

If this can help the maintainer, what config are you using ? Here I am in full static.

**Comment by wobsoriano** [comment]
Interesting because the website itself is using Next 13

**Comment by thebuilder** [comment]
Comparing them, it appears to be all the minified variable names that differ.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/3764345/209467527-d49f8467-5a2a-4143-9c38-026f309dde72.png">

**Comment by shuding** [comment]
Fixed with #12, please try https://github.com/shuding/react-wrap-balancer/releases/tag/0.2.4
