### ISSUE TITLE
Option to force logic whether browser supports `text-wrap: balancer`

### ISSUE THREAD

**Issue by hiddenest** [shuding/react-wrap-balancer#75]
There are still some issue with native `text-wrap: balancer`, especially with CJK letters.
If there is an option to force balancer logic without checking browser supports, it could be awesome.

For Example,
:x: **Native `text-wrap: balancer`:**
<img width="423" alt="스크린샷 2023-06-30 오후 5 53 04" src="https://github.com/shuding/react-wrap-balancer/assets/8682478/c6b3f920-2b59-4b4b-ab60-34430c53d3e6">

✅  **`react-wrap-balancer` v0.5.0:**
<img width="410" alt="스크린샷 2023-06-30 오후 5 57 09" src="https://github.com/shuding/react-wrap-balancer/assets/8682478/7b5e79ee-38d3-4e0f-b7a8-27135ebf3150">

**Comment by shuding** [comment]
We can probably have an option for this 👍
