### ISSUE TITLE
Extra line is being added 😢

### ISSUE THREAD

**Issue by MananTank** [shuding/react-wrap-balancer#8]
## without wrap-balancer 

<img width="992" alt="image" src="https://user-images.githubusercontent.com/22043396/209357161-39c1a812-7bc8-429f-91aa-5e08896b91fc.png">

## with wrap-balancer

<img width="939" alt="image" src="https://user-images.githubusercontent.com/22043396/209357056-f3fd6845-1b84-457f-81c7-9b3f34755c0f.png">

Here's how the HTML looks like: 

<img width="977" alt="image" src="https://user-images.githubusercontent.com/22043396/209357279-74b8caf2-1169-4819-b7ea-e72595e42572.png">

**Comment by shuding** [comment]
Can you share your original code? E.g. did you do `<h2><Balancer>Think multi-chain</Balancer></h2>`? From the HTML it doesn't seem like the library is used.

**Comment by MananTank** [comment]
@shuding Yeah, I'm showing the HTML when the library is not used. - to show that I'm just inserting plain text in the heading

**Comment by shuding** [comment]
Is it possible to provide a reproduction on https://codesandbox.io?
